version: '3.8'

services:
  api:
    image: encurtador-url
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - encurtador-url-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    networks:
      - encurtador-url-network
    expose:
      - 5432
networks:
  encurtador-url-network:
    driver: bridge
